import { RxCursorArrow } from "react-icons/rx";

export const routesData = {
  product: [
    {
      label: "Designer",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "CMS",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Interaction",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Localization",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Ecommerce",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Hosting",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "SEO",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Editor",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Security",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Figma to Webflow",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "DevLink",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Feature Index",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Accessibility",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  compare: [
    {
      label: "Webflow vs WordPress",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Webflow vs Squarespace",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Webflow vs Shopify",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Webflow vs Contentful",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  company: [
    {
      label: "About",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Careers",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Press",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Merch store",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Accessibility statement",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Terms of Service",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Privacy policy",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Cookie policy",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Cookie preferences",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Sitemap",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  solutions: [
    {
      label: "Freelance and agencies",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Enterprise",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Staryups",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Classrooms",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  explore: [
    {
      label: "Marketplace",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Libraries",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Apps",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Hire an Expert",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Templates",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Made in Webflow",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  learn: [
    {
      label: "University",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Blog",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Customers",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Resources",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Community",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Developers",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Glossary",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  partner: [
    {
      label: "Become an Expert",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Become a Template Designer",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Become an Affiliate",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
  help: [
    {
      label: "Suppert",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Pricing",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Status",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Forum",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
    {
      label: "Wishlist",
      route: "/",
      icon: <RxCursorArrow />,
      description: "Lorem Ipsum is Lorem Ipsum and   Lorem Ipsum is Lorem",
    },
  ],
};
